name: release

on: push

jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Change version
        run: |
          version=$(git describe --abbrev=0 --tags)
          sed -i -e "s/0.0.0/$version/g" package.json
          cat package.json

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: true

      - name: Build
        run: |
          pnpm build

      - name: Generate changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}

      - name: Publish npm
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
